### ISSUE TITLE
[Mint-X Gtk 3 theme] Header bars of windows with CSD have very dark gradient

### ISSUE THREAD

**Issue by Odyseus** [linuxmint/mint-themes#238]
Since the update of the Mint-X Gtk 3 theme from Gtk 3.18 to Gtk 3.22, I observed that the header bars for windows with CSD (Client Side Decorations) were darker. I thought at first that it was a design decision, but while looking at how to get the previous style (for my own fork of the theme), I saw that the style was exactly the same as in the past version ([L728](https://github.com/linuxmint/mint-themes/blob/master/src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css#L728) and [L745](https://github.com/linuxmint/mint-themes/blob/master/src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css#L745)) and that it was overridden by a [workaround](https://github.com/linuxmint/mint-themes/blob/master/src/Mint-X/theme/Mint-X/gtk-3.0/gtk-widgets.css#L866) added to fix some irregularities with some applications.

This is how windows with CSD look like currently:

![header-too-dark](https://user-images.githubusercontent.com/3822556/73041035-a70e9f00-3e3a-11ea-9680-a417c82da62c.png)

This is how windows with CSD looked like previously:

![header-fixed](https://user-images.githubusercontent.com/3822556/73041036-a7a73580-3e3a-11ea-99ab-a65fed25f51c.png)

The main *aesthetic problem* that I see overall with the current style is that the dark header bars add a lot of contrast in relation with all other elements inside the header and the window itself in addition to greatly reduce the contrast of the text. To *fix* this I slightly modified the CSS selectors for the workaround rules as follows:

```css
/* Workaround for header bars that are moved out of position in apps like
 * gnome-system-monitor in non gnome destkops */
window.background:not(.csd) headerbar {
    box-shadow: none;
    background-color: transparent;
    background-image: linear-gradient(to bottom, @toolbar_bg_a, @toolbar_bg_b);
}

window.background:not(.csd) headerbar:backdrop {
    background-color: transparent;
    background-image: linear-gradient(to bottom, @toolbar_bg_a, @toolbar_bg_b);
}
```

I simply changed the `:not(csd)` pseudo-class to `:not(.csd)` in both rules. Since I didn't see the `csd` tag used anywhere in any theme on this repository, I assumed that it was a typo and changed it to a class (a shot in the dark really LOL).

I know that this fixes the issue that I describe with the header bars, but I don't know if it is the right way of fixing it. So, I will let the experts decide (@smurphos & @JosephMcc).
