### ISSUE TITLE
Mint-Y: Gtk.Separator contarst / parameterization

### ISSUE THREAD

**Issue by vec2pt** [linuxmint/mint-themes#482]
It would be nice to increase the [Gtk.Separator](https://docs.gtk.org/gtk4/class.Separator.html) contrast in the Mint-Y dark version. In addition, I noticed that the separators' color is not parameterized.

Currently, the separators look like:

![Screenshot from 2024-11-08 22-21-19](https://github.com/user-attachments/assets/039abf90-ba22-4ee1-82b0-9d2b64bd14ce)

## Solution

It would be possible to parametrize ` background-color` with the ` $separator_color` variable.

```scss
 //vbox and hbox separators 
 separator { 
   background-color: $separator_color;
   min-width: 1px; 
   min-height: 1px; 
 } 
```

https://github.com/linuxmint/mint-themes/blob/5de93c0c55b98526e90e087afdcb2a4bb78d3070/src/Mint-Y/gtk-3.0/sass/_common.scss#L2431-L2436

https://github.com/linuxmint/mint-themes/blob/5de93c0c55b98526e90e087afdcb2a4bb78d3070/src/Mint-Y/gtk-4.0/sass/_common.scss#L2642-L2647

Print Screen after making changes:

![Screenshot from 2024-11-08 22-23-50](https://github.com/user-attachments/assets/f56f8e2c-6723-4f1f-88d0-436c497a8a0e)
